sudo: required

language: node_js

env:
  global:
    IMAGE_NAME=corp/my_node
    DOCKER_USERNAME=mattb912
    DOCKER_PASSWORD=s3dd8zdCVK

services:
  - docker

before_script:
    - version="$(awk '$2 == "MY_APP" { print $3; exit}' Dockerfile)"

script:
  - docker build -t "$IMAGE_NAME" .

after_script:
  - docker images 

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker tag my_node-dev $DOCKER_USERNAME/my_node-dev:${version}

deploy:
  provider: script
  script: docker push $DOCKER_USERNAME/my_node-dev:${version}
  on:
    branches:
    only:
      - dev
      - qa 
      - master
  
  notifications:
    email:
      - mattb.912@gmail.com
  
