sudo: required

language: node_js

env:
  DOCKER_USERNAME=mattb912
  DOCKER_PASSWORD=s3dd8zdCVK

services:
  - docker

stages:
  - name: build dev image
    if: branch = dev
jobs:
  include:
    - stage: build dev image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t my_node-dev .
      - docker images 
      - docker tag my_node-dev $DOCKER_USERNAME/my_node-dev 
      - docker push $DOCKER_USERNAME/my_node-dev

    - name: build dev image
      if: branch = qa
        

    - stage: build QA image
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t my_node-qa .
        - docker images 
        - docker tag my_node-dev $DOCKER_USERNAME/my_node-qa 
        - docker push $DOCKER_USERNAME/my_node-qa

    - name: build PRODUCTION image
      if: branch = MASTER

    - stage: build PROD image
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t my_node-prod .
        - docker images 
        - docker tag my_node-dev $DOCKER_USERNAME/my_node-prod 
        - docker push $DOCKER_USERNAME/my_node-prod