sudo: required

language: node_js

env:
  global:
    IMAGE_NAME=my_node
    DOCKER_USERNAME=mattb912
    DOCKER_PASSWORD=s3dd8zdCVK

services:
  - docker

before_script:
    - version="$(awk '$2 == "MY_APP" { print $3; exit}' Dockerfile)"
    - BRANCH=$TRAVIS_BRANCH
    - echo "${BRANCH}"


script:
  - docker build -t "$IMAGE_NAME" .
  - docker images 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker tag my_node $DOCKER_USERNAME/my_node-${BRANCH}:latest
  - docker tag my_node $DOCKER_USERNAME/my_node-${BRANCH}:${version}

deploy:
  
    provider: script
    script: docker push $DOCKER_USERNAME/my_node-${BRANCH}:${version} && docker push $DOCKER_USERNAME/my_node-${BRANCH}:latest
    skip_cleanup: true
    on:
      branch:
        dev
        qa
        master

notifications:
    email:
      - mattb.912@gmail.com
  
