sudo: required

language: node_js

env:
  global:
    IMAGE_NAME=my_node
    DOCKER_USERNAME=mattb912
    DOCKER_PASSWORD=s3dd8zdCVK

services:
  - docker

before_script:
    - version="$(awk '$2 == "MY_APP" { print $3; exit}' Dockerfile)"
    - export BRANCH=$(if [ ${TRAVIS_PULL_REQUEST} = "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
    - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"


script:
  - docker build -t "$IMAGE_NAME" .

after_script:
  - docker images 

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker tag my_node $DOCKER_USERNAME/my_node-${BRANCH}:latest
  - docker tag my_node $DOCKER_USERNAME/my_node-${BRANCH}:${version}

deploy:
  provider: script
  script: docker push $DOCKER_USERNAME/my_node-${BRANCH}:${version} && docker push $DOCKER_USERNAME/my_node-${BRANCH}:latest
  on:
    branch:
      dev
      qa
      master

notifications:
    email:
      - mattb.912@gmail.com
  
