sudo: required

language: node_js


services:
  - docker

before_script:
    - version="$(awk '$2 == "MY_APP" { print $3; exit}' Dockerfile)"
    - BRANCH=$TRAVIS_BRANCH
    - echo "${BRANCH}"

script:
    - if [ $TRAVIS_BRANCH == "dev" || $TRAVIS_BRANCH == "qa" || $TRAVIS_BRANCH == "master"  ]; then bash build_image.sh ${BRANCH}; fi

notifications:
    slack: mattgroup-workspace:Ibymbc5Lvz613oXoNyBGZGwC


  
